/* tslint:disable */
/* eslint-disable */
/**
 * Trillion Trees Campaign
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Contribution
 */
export interface Contribution {
    /**
     * 
     * @type {number}
     * @memberof Contribution
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Contribution
     */
    contributionType: string;
    /**
     * 
     * @type {string}
     * @memberof Contribution
     */
    cardType: string;
    /**
     * 
     * @type {number}
     * @memberof Contribution
     */
    treeCount: number;
    /**
     * 
     * @type {string}
     * @memberof Contribution
     */
    plantDate: string;
    /**
     * 
     * @type {number}
     * @memberof Contribution
     */
    geoLongitude: number;
    /**
     * 
     * @type {number}
     * @memberof Contribution
     */
    geoLatitude: number;
    /**
     * 
     * @type {string}
     * @memberof Contribution
     */
    country: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Contribution
     */
    contributionImages: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Contribution
     */
    treeType: string;
    /**
     * 
     * @type {string}
     * @memberof Contribution
     */
    treeSpecies: string;
    /**
     * 
     * @type {string}
     * @memberof Contribution
     */
    treeClassification: string;
    /**
     * 
     * @type {string}
     * @memberof Contribution
     */
    treeScientificName: string;
    /**
     * 
     * @type {boolean}
     * @memberof Contribution
     */
    mayUpdate: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Contribution
     */
    isGift: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Contribution
     */
    isPending: boolean;
    /**
     * 
     * @type {string}
     * @memberof Contribution
     */
    registrationDate: string;
    /**
     * 
     * @type {string}
     * @memberof Contribution
     */
    givee: string;
    /**
     * 
     * @type {string}
     * @memberof Contribution
     */
    giveeSlug: string;
    /**
     * 
     * @type {string}
     * @memberof Contribution
     */
    ndviUid: string;
    /**
     * 
     * @type {object}
     * @memberof Contribution
     */
    context?: object;
    /**
     * 
     * @type {string}
     * @memberof Contribution
     */
    geometry?: string;
}

export function ContributionFromJSON(json: any): Contribution {
    return ContributionFromJSONTyped(json, false);
}

export function ContributionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Contribution {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'contributionType': json['contributionType'],
        'cardType': json['cardType'],
        'treeCount': json['treeCount'],
        'plantDate': json['plantDate'],
        'geoLongitude': json['geoLongitude'],
        'geoLatitude': json['geoLatitude'],
        'country': json['country'],
        'contributionImages': json['contributionImages'],
        'treeType': json['treeType'],
        'treeSpecies': json['treeSpecies'],
        'treeClassification': json['treeClassification'],
        'treeScientificName': json['treeScientificName'],
        'mayUpdate': json['mayUpdate'],
        'isGift': json['isGift'],
        'isPending': json['isPending'],
        'registrationDate': json['registrationDate'],
        'givee': json['givee'],
        'giveeSlug': json['giveeSlug'],
        'ndviUid': json['ndviUid'],
        'context': !exists(json, 'context') ? undefined : json['context'],
        'geometry': !exists(json, 'geometry') ? undefined : json['geometry'],
    };
}

export function ContributionToJSON(value?: Contribution | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'contributionType': value.contributionType,
        'cardType': value.cardType,
        'treeCount': value.treeCount,
        'plantDate': value.plantDate,
        'geoLongitude': value.geoLongitude,
        'geoLatitude': value.geoLatitude,
        'country': value.country,
        'contributionImages': value.contributionImages,
        'treeType': value.treeType,
        'treeSpecies': value.treeSpecies,
        'treeClassification': value.treeClassification,
        'treeScientificName': value.treeScientificName,
        'mayUpdate': value.mayUpdate,
        'isGift': value.isGift,
        'isPending': value.isPending,
        'registrationDate': value.registrationDate,
        'givee': value.givee,
        'giveeSlug': value.giveeSlug,
        'ndviUid': value.ndviUid,
        'context': value.context,
        'geometry': value.geometry,
    };
}


