/* tslint:disable */
/* eslint-disable */
/**
 * Trillion Trees Campaign
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Gift
 */
export interface Gift {
    /**
     * 
     * @type {number}
     * @memberof Gift
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Gift
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof Gift
     */
    cardType?: string;
    /**
     * 
     * @type {number}
     * @memberof Gift
     */
    treeCount?: number;
    /**
     * 
     * @type {string}
     * @memberof Gift
     */
    redemptionDate?: string;
    /**
     * 
     * @type {number}
     * @memberof Gift
     */
    geoLongitude?: number;
    /**
     * 
     * @type {number}
     * @memberof Gift
     */
    geoLatitude?: number;
    /**
     * 
     * @type {string}
     * @memberof Gift
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof Gift
     */
    treeType?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Gift
     */
    isPending?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Gift
     */
    treeSpecies?: string;
}

export function GiftFromJSON(json: any): Gift {
    return GiftFromJSONTyped(json, false);
}

export function GiftFromJSONTyped(json: any, ignoreDiscriminator: boolean): Gift {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'cardType': !exists(json, 'cardType') ? undefined : json['cardType'],
        'treeCount': !exists(json, 'treeCount') ? undefined : json['treeCount'],
        'redemptionDate': !exists(json, 'redemptionDate') ? undefined : json['redemptionDate'],
        'geoLongitude': !exists(json, 'geoLongitude') ? undefined : json['geoLongitude'],
        'geoLatitude': !exists(json, 'geoLatitude') ? undefined : json['geoLatitude'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'treeType': !exists(json, 'treeType') ? undefined : json['treeType'],
        'isPending': !exists(json, 'isPending') ? undefined : json['isPending'],
        'treeSpecies': !exists(json, 'treeSpecies') ? undefined : json['treeSpecies'],
    };
}

export function GiftToJSON(value?: Gift | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'type': value.type,
        'cardType': value.cardType,
        'treeCount': value.treeCount,
        'redemptionDate': value.redemptionDate,
        'geoLongitude': value.geoLongitude,
        'geoLatitude': value.geoLatitude,
        'country': value.country,
        'treeType': value.treeType,
        'isPending': value.isPending,
        'treeSpecies': value.treeSpecies,
    };
}


