/* tslint:disable */
/* eslint-disable */
/**
 * Trillion Trees Campaign
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LeaderboardBreadcrumb,
    LeaderboardBreadcrumbFromJSON,
    LeaderboardBreadcrumbFromJSONTyped,
    LeaderboardBreadcrumbToJSON,
    LeaderboardEntry,
    LeaderboardEntryFromJSON,
    LeaderboardEntryFromJSONTyped,
    LeaderboardEntryToJSON,
} from './';

/**
 * 
 * @export
 * @interface InlineResponse2001
 */
export interface InlineResponse2001 {
    /**
     * 
     * @type {LeaderboardBreadcrumb}
     * @memberof InlineResponse2001
     */
    self?: LeaderboardBreadcrumb;
    /**
     * 
     * @type {LeaderboardBreadcrumb}
     * @memberof InlineResponse2001
     */
    parent?: LeaderboardBreadcrumb;
    /**
     * 
     * @type {Array<LeaderboardEntry>}
     * @memberof InlineResponse2001
     */
    data?: Array<LeaderboardEntry>;
}

export function InlineResponse2001FromJSON(json: any): InlineResponse2001 {
    return InlineResponse2001FromJSONTyped(json, false);
}

export function InlineResponse2001FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2001 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'self': !exists(json, 'self') ? undefined : LeaderboardBreadcrumbFromJSON(json['self']),
        'parent': !exists(json, 'parent') ? undefined : LeaderboardBreadcrumbFromJSON(json['parent']),
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(LeaderboardEntryFromJSON)),
    };
}

export function InlineResponse2001ToJSON(value?: InlineResponse2001 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'self': LeaderboardBreadcrumbToJSON(value.self),
        'parent': LeaderboardBreadcrumbToJSON(value.parent),
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(LeaderboardEntryToJSON)),
    };
}


