/* tslint:disable */
/* eslint-disable */
/**
 * Trillion Trees Campaign
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LeaderboardBreadcrumb
 */
export interface LeaderboardBreadcrumb {
    /**
     * 
     * @type {string}
     * @memberof LeaderboardBreadcrumb
     */
    caption: string;
    /**
     * 
     * @type {string}
     * @memberof LeaderboardBreadcrumb
     */
    uri: string;
}

export function LeaderboardBreadcrumbFromJSON(json: any): LeaderboardBreadcrumb {
    return LeaderboardBreadcrumbFromJSONTyped(json, false);
}

export function LeaderboardBreadcrumbFromJSONTyped(json: any, ignoreDiscriminator: boolean): LeaderboardBreadcrumb {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'caption': json['caption'],
        'uri': json['uri'],
    };
}

export function LeaderboardBreadcrumbToJSON(value?: LeaderboardBreadcrumb | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'caption': value.caption,
        'uri': value.uri,
    };
}


