/* tslint:disable */
/* eslint-disable */
/**
 * Trillion Trees Campaign
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MenuSection,
    MenuSectionFromJSON,
    MenuSectionFromJSONTyped,
    MenuSectionToJSON,
} from './';

/**
 * 
 * @export
 * @interface Menu
 */
export interface Menu extends Array<MenuSection> {
}

export function MenuFromJSON(json: any): Menu {
    return MenuFromJSONTyped(json, false);
}

export function MenuFromJSONTyped(json: any, ignoreDiscriminator: boolean): Menu {
    return json;
}

export function MenuToJSON(value?: Menu | null): any {
    return value;
}


