/* tslint:disable */
/* eslint-disable */
/**
 * Trillion Trees Campaign
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlantProjectImage
 */
export interface PlantProjectImage {
    /**
     * 
     * @type {number}
     * @memberof PlantProjectImage
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PlantProjectImage
     */
    image: string;
    /**
     * 
     * @type {string}
     * @memberof PlantProjectImage
     */
    description?: string;
}

export function PlantProjectImageFromJSON(json: any): PlantProjectImage {
    return PlantProjectImageFromJSONTyped(json, false);
}

export function PlantProjectImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlantProjectImage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'image': json['image'],
        'description': !exists(json, 'description') ? undefined : json['description'],
    };
}

export function PlantProjectImageToJSON(value?: PlantProjectImage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'image': value.image,
        'description': value.description,
    };
}


