/* tslint:disable */
/* eslint-disable */
/**
 * Trillion Trees Campaign
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PlantProjectPagerMergePlantProjectPager,
    PlantProjectPagerMergePlantProjectPagerFromJSON,
    PlantProjectPagerMergePlantProjectPagerFromJSONTyped,
    PlantProjectPagerMergePlantProjectPagerToJSON,
} from './';

/**
 * 
 * @export
 * @interface PlantProjectPagerMerge
 */
export interface PlantProjectPagerMerge {
    /**
     * 
     * @type {PlantProjectPagerMergePlantProjectPager}
     * @memberof PlantProjectPagerMerge
     */
    plantProjectPager?: PlantProjectPagerMergePlantProjectPager;
}

export function PlantProjectPagerMergeFromJSON(json: any): PlantProjectPagerMerge {
    return PlantProjectPagerMergeFromJSONTyped(json, false);
}

export function PlantProjectPagerMergeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlantProjectPagerMerge {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'plantProjectPager': !exists(json, 'plantProjectPager') ? undefined : PlantProjectPagerMergePlantProjectPagerFromJSON(json['plantProjectPager']),
    };
}

export function PlantProjectPagerMergeToJSON(value?: PlantProjectPagerMerge | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'plantProjectPager': PlantProjectPagerMergePlantProjectPagerToJSON(value.plantProjectPager),
    };
}


