/* tslint:disable */
/* eslint-disable */
/**
 * Trillion Trees Campaign
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlantProjectAllOfTreeCountOptions
 */
export interface PlantProjectAllOfTreeCountOptions {
    /**
     * 
     * @type {number}
     * @memberof PlantProjectAllOfTreeCountOptions
     */
    _default?: number;
    /**
     * 
     * @type {number}
     * @memberof PlantProjectAllOfTreeCountOptions
     */
    option1?: number;
    /**
     * 
     * @type {number}
     * @memberof PlantProjectAllOfTreeCountOptions
     */
    option2?: number;
    /**
     * 
     * @type {number}
     * @memberof PlantProjectAllOfTreeCountOptions
     */
    option3?: number;
    /**
     * 
     * @type {number}
     * @memberof PlantProjectAllOfTreeCountOptions
     */
    option4?: number;
}

export function PlantProjectAllOfTreeCountOptionsFromJSON(json: any): PlantProjectAllOfTreeCountOptions {
    return PlantProjectAllOfTreeCountOptionsFromJSONTyped(json, false);
}

export function PlantProjectAllOfTreeCountOptionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlantProjectAllOfTreeCountOptions {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        '_default': !exists(json, 'default') ? undefined : json['default'],
        'option1': !exists(json, 'option1') ? undefined : json['option1'],
        'option2': !exists(json, 'option2') ? undefined : json['option2'],
        'option3': !exists(json, 'option3') ? undefined : json['option3'],
        'option4': !exists(json, 'option4') ? undefined : json['option4'],
    };
}

export function PlantProjectAllOfTreeCountOptionsToJSON(value?: PlantProjectAllOfTreeCountOptions | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'default': value._default,
        'option1': value.option1,
        'option2': value.option2,
        'option3': value.option3,
        'option4': value.option4,
    };
}


