/* tslint:disable */
/* eslint-disable */
/**
 * Trillion Trees Campaign
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PlantProjectPagerMerge,
    PlantProjectPagerMergeFromJSON,
    PlantProjectPagerMergeFromJSONTyped,
    PlantProjectPagerMergeToJSON,
} from './';

/**
 * Paginated list of PlantProjects
 * @export
 * @interface PlantProjectPager
 */
export interface PlantProjectPager {
    /**
     * 
     * @type {PlantProjectPagerMerge}
     * @memberof PlantProjectPager
     */
    merge?: PlantProjectPagerMerge;
}

export function PlantProjectPagerFromJSON(json: any): PlantProjectPager {
    return PlantProjectPagerFromJSONTyped(json, false);
}

export function PlantProjectPagerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlantProjectPager {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'merge': !exists(json, 'merge') ? undefined : PlantProjectPagerMergeFromJSON(json['merge']),
    };
}

export function PlantProjectPagerToJSON(value?: PlantProjectPager | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'merge': PlantProjectPagerMergeToJSON(value.merge),
    };
}


