/* tslint:disable */
/* eslint-disable */
/**
 * Trillion Trees Campaign
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * PlantProject summary display for paginated results
 * @export
 * @interface PlantProjectSummary
 */
export interface PlantProjectSummary {
    /**
     * 
     * @type {number}
     * @memberof PlantProjectSummary
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof PlantProjectSummary
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof PlantProjectSummary
     */
    countTarget: number;
    /**
     * 
     * @type {number}
     * @memberof PlantProjectSummary
     */
    survivalRate: number;
    /**
     * 
     * @type {number}
     * @memberof PlantProjectSummary
     */
    treeCost: number;
    /**
     * 
     * @type {string}
     * @memberof PlantProjectSummary
     */
    currency: string;
    /**
     * 
     * @type {string}
     * @memberof PlantProjectSummary
     */
    url: string;
    /**
     * 
     * @type {string}
     * @memberof PlantProjectSummary
     */
    tpoSlug: string;
    /**
     * 
     * @type {string}
     * @memberof PlantProjectSummary
     */
    country?: string;
    /**
     * 
     * @type {string}
     * @memberof PlantProjectSummary
     */
    tpoName?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PlantProjectSummary
     */
    taxDeductibleCountries?: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof PlantProjectSummary
     */
    hasTaxDeduction?: boolean;
    /**
     * 
     * @type {string}
     * @memberof PlantProjectSummary
     */
    slug?: string;
    /**
     * 
     * @type {number}
     * @memberof PlantProjectSummary
     */
    reviewScore?: number;
    /**
     * 
     * @type {number}
     * @memberof PlantProjectSummary
     */
    countPlanted?: number;
    /**
     * 
     * @type {string}
     * @memberof PlantProjectSummary
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof PlantProjectSummary
     */
    survivalRateStatus?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PlantProjectSummary
     */
    isFeatured?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof PlantProjectSummary
     */
    allowDonations?: boolean;
}

export function PlantProjectSummaryFromJSON(json: any): PlantProjectSummary {
    return PlantProjectSummaryFromJSONTyped(json, false);
}

export function PlantProjectSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlantProjectSummary {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'countTarget': json['countTarget'],
        'survivalRate': json['survivalRate'],
        'treeCost': json['treeCost'],
        'currency': json['currency'],
        'url': json['url'],
        'tpoSlug': json['tpoSlug'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'tpoName': !exists(json, 'tpoName') ? undefined : json['tpoName'],
        'taxDeductibleCountries': !exists(json, 'taxDeductibleCountries') ? undefined : json['taxDeductibleCountries'],
        'hasTaxDeduction': !exists(json, 'hasTaxDeduction') ? undefined : json['hasTaxDeduction'],
        'slug': !exists(json, 'slug') ? undefined : json['slug'],
        'reviewScore': !exists(json, 'reviewScore') ? undefined : json['reviewScore'],
        'countPlanted': !exists(json, 'countPlanted') ? undefined : json['countPlanted'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'survivalRateStatus': !exists(json, 'survivalRateStatus') ? undefined : json['survivalRateStatus'],
        'isFeatured': !exists(json, 'isFeatured') ? undefined : json['isFeatured'],
        'allowDonations': !exists(json, 'allowDonations') ? undefined : json['allowDonations'],
    };
}

export function PlantProjectSummaryToJSON(value?: PlantProjectSummary | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'countTarget': value.countTarget,
        'survivalRate': value.survivalRate,
        'treeCost': value.treeCost,
        'currency': value.currency,
        'url': value.url,
        'tpoSlug': value.tpoSlug,
        'country': value.country,
        'tpoName': value.tpoName,
        'taxDeductibleCountries': value.taxDeductibleCountries,
        'hasTaxDeduction': value.hasTaxDeduction,
        'slug': value.slug,
        'reviewScore': value.reviewScore,
        'countPlanted': value.countPlanted,
        'image': value.image,
        'survivalRateStatus': value.survivalRateStatus,
        'isFeatured': value.isFeatured,
        'allowDonations': value.allowDonations,
    };
}


