/* tslint:disable */
/* eslint-disable */
/**
 * Trillion Trees Campaign
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PledgeEvent
 */
export interface PledgeEvent {
    /**
     * 
     * @type {string}
     * @memberof PledgeEvent
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof PledgeEvent
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PledgeEvent
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof PledgeEvent
     */
    total: number;
    /**
     * 
     * @type {string}
     * @memberof PledgeEvent
     */
    image: string;
    /**
     * 
     * @type {number}
     * @memberof PledgeEvent
     */
    position: number;
}

export function PledgeEventFromJSON(json: any): PledgeEvent {
    return PledgeEventFromJSONTyped(json, false);
}

export function PledgeEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): PledgeEvent {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'slug': json['slug'],
        'name': json['name'],
        'description': json['description'],
        'total': json['total'],
        'image': json['image'],
        'position': json['position'],
    };
}

export function PledgeEventToJSON(value?: PledgeEvent | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'slug': value.slug,
        'name': value.name,
        'description': value.description,
        'total': value.total,
        'image': value.image,
        'position': value.position,
    };
}


