/* tslint:disable */
/* eslint-disable */
/**
 * Trillion Trees Campaign
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfile
 */
export interface UserProfile {
    /**
     * 
     * @type {number}
     * @memberof UserProfile
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    fullname?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    synopsis1?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    synopsis2?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    linkText?: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfile
     */
    url?: string;
}

export function UserProfileFromJSON(json: any): UserProfile {
    return UserProfileFromJSONTyped(json, false);
}

export function UserProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'fullname': !exists(json, 'fullname') ? undefined : json['fullname'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'synopsis1': !exists(json, 'synopsis1') ? undefined : json['synopsis1'],
        'synopsis2': !exists(json, 'synopsis2') ? undefined : json['synopsis2'],
        'linkText': !exists(json, 'linkText') ? undefined : json['linkText'],
        'url': !exists(json, 'url') ? undefined : json['url'],
    };
}

export function UserProfileToJSON(value?: UserProfile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'fullname': value.fullname,
        'name': value.name,
        'type': value.type,
        'image': value.image,
        'synopsis1': value.synopsis1,
        'synopsis2': value.synopsis2,
        'linkText': value.linkText,
        'url': value.url,
    };
}


